/**
 * app/api/speak/route.ts — Cartesia Sonic TTS proxy (voice-out)
 *
 * The agent's spoken replies are generated by Cartesia Sonic, server-side. The
 * client POSTs the decision sentence here; this route calls Cartesia's TTS
 * /tts/bytes endpoint with the server-held API key and streams the mp3 back.
 *
 * WHY A SERVER PROXY (not a client-side key or ephemeral token):
 *   - The CARTESIA_API_KEY never leaves the server — the browser only ever sees
 *     audio bytes, never the credential. Safe to run from a public deployment.
 *   - For a short, one-shot decision sentence a request/response proxy is simpler
 *     and more reliable than a client WebSocket (which is what a low-latency,
 *     real-time duplex agent like a phone bot would use instead).
 *
 * UNCONFIGURED (CI / local dev without a key):
 *   Returns 501 { error: "not_configured" }. The client treats any non-200 as a
 *   signal to fall back to the browser-native Web Speech API, so voice still
 *   works keyless — just with the OS voice instead of Cartesia.
 *
 * @see https://docs.cartesia.ai/api-reference/tts/bytes
 */

export const runtime = "nodejs";

/** Pin the Cartesia API version we tested against. */
const CARTESIA_VERSION = "2024-11-13";
/** Default Sonic voice. Override per-deployment with CARTESIA_VOICE_ID. */
const DEFAULT_VOICE_ID = "694f9389-aac1-45b6-b726-9d9369183238";
/** Hard cap on TTS input — decision sentences are short; this prevents abuse. */
const MAX_TTS_CHARS = 600;

export async function POST(req: Request): Promise<Response> {
  const apiKey = process.env.CARTESIA_API_KEY;

  // ── Unconfigured: client falls back to Web Speech ─────────────────────────
  if (!apiKey) {
    return Response.json(
      {
        error: "not_configured",
        detail:
          "CARTESIA_API_KEY is not set. The client falls back to the browser-native " +
          "Web Speech API for voice output. Set CARTESIA_API_KEY server-side to enable " +
          "the Cartesia Sonic voice.",
      },
      { status: 501 },
    );
  }

  // ── Parse + validate the input text ───────────────────────────────────────
  let body: { text?: unknown };
  try {
    body = (await req.json()) as { text?: unknown };
  } catch {
    return Response.json({ error: "bad_request" }, { status: 400 });
  }

  const text =
    typeof body.text === "string" ? body.text.trim().slice(0, MAX_TTS_CHARS) : "";
  if (text.length === 0) {
    return Response.json({ error: "bad_request" }, { status: 400 });
  }

  // ── Call Cartesia Sonic — key stays server-side ───────────────────────────
  const voiceId = process.env.CARTESIA_VOICE_ID || DEFAULT_VOICE_ID;
  try {
    const res = await fetch("https://api.cartesia.ai/tts/bytes", {
      method: "POST",
      headers: {
        "X-API-Key": apiKey,
        "Cartesia-Version": CARTESIA_VERSION,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model_id: "sonic-2",
        transcript: text,
        voice: { mode: "id", id: voiceId },
        output_format: { container: "mp3", sample_rate: 44100, bit_rate: 128000 },
        language: "en",
      }),
    });

    if (!res.ok) {
      const detail = (await res.text().catch(() => "")).slice(0, 200);
      return Response.json(
        { error: "tts_failed", status: res.status, detail },
        { status: 502 },
      );
    }

    const audio = await res.arrayBuffer();
    return new Response(audio, {
      status: 200,
      headers: {
        "Content-Type": "audio/mpeg",
        "Cache-Control": "no-store",
      },
    });
  } catch {
    return Response.json(
      { error: "tts_failed", detail: "Failed to reach the Cartesia TTS endpoint." },
      { status: 502 },
    );
  }
}
